[Variables]
Size=16
Font=Classic Console
FontAlias=0
FontWeight=100
Accent=255,255,255

;//////////////////////////////////////////////////////////////////////
;//////////////////////////////////////////////////////////////////////
;//////////////////////////////////////////////////////////////////////

[Prefix]
Text=Starting MS-DOS...#CRLF##CRLF#HIMEM is testing extended memory ... done.#CRLF#C:\>C:\DOS\SMARTDRV.exe /X#CRLF#C:\>CD RAINMETER~1#CRLF#C:\RAINME~1>PLAINEXT.EXE

[Title]
FontWeight=#FontWeight#
Y=10R
Fontsize=(#Size#*2)
Text=%1 %2
InlinePattern=\s(.*)
InlineSetting=Size | (#Size#+8)
LeftMouseUpAction=[]
RightMouseUpAction=[]
