[MeasureTopUsage1CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=1
Substitute="":"."

[MeasureTopUsage2CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=2
Substitute="":"."

[MeasureTopUsage3CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=3
Substitute="":"."

[MeasureTopUsage4CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=4
Substitute="":"."

[MeasureTopUsage5CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=5
Substitute="":"."

[MeasureTopUsage6CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=6
Substitute="":"."