
;//////////////////////////////////////////////////////////////////////
;//////////////////////////////////////////////////////////////////////
;//////////////////////////////////////////////////////////////////////

[Prefix]
Text=Starting MS-DOS...#CRLF##CRLF#HIMEM is testing extended memory ... done.#CRLF#C:\>C:\DOS\SMARTDRV.exe /X#CRLF#C:\>CD RAINMETER~1#CRLF#C:\RAINME~1>PLAINEXT.EXE

[Title]
FontWeight=#FontWeight#
Y=10R
Fontsize=(#Scale#*2)
Text=%1 %2
InlinePattern=\s(.*)
InlineSetting=Size | (#Scale#+8)
LeftMouseUpAction=[]
RightMouseUpAction=[]
