[MeasureTopUsage1CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=1
Substitute="":"."
Group=NonOverview

[MeasureTopUsage2CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=2
Substitute="":"."
Group=NonOverview

[MeasureTopUsage3CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=3
Substitute="":"."
Group=NonOverview

[MeasureTopUsage4CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=4
Substitute="":"."
Group=NonOverview

[MeasureTopUsage5CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=5
Substitute="":"."
Group=NonOverview

[MeasureTopUsage6CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=6
Substitute="":"."
Group=NonOverview