
[Text]
X=r
Y=R
FontSize=#Scale#
FontFace=#Font#
AntiAlias=#FontAlias#
StringAlign=#Side#
FontColor=#FontColor#
FontWeight=#FontWeight#
SolidColor=0, 0, 0, 1
Group=Wildcard

[Dots]
X=#in#
Y=R
AntiAlias=#FontAlias#
FontSize=#Scale#
StringAlign=#Side#
FontColor=#FontColor#
SolidColor=0, 0, 0, 1
Text=-----------------------
FontWeight=900
Group=Wildcard
FontFace=#Font#

[VBar]
X=5R
Y=r
AntiAlias=#FontAlias#
FontSize=#Scale#
StringAlign=#Side#
FontColor=#FontColor#
SolidColor=0, 0, 0, 1
Text=|#CRLF#|#CRLF#|#CRLF#|#CRLF#|#CRLF#|#CRLF#
fontface=#Font#
Group=Wildcard